# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  default_locale: ru
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  #http_method_override: true

  session:
    handler_id: Symfony\Component\HttpFoundation\Session\Storage\Handler\RedisSessionHandler
    cookie_secure: auto
    cookie_samesite: lax

  #esi: true
  #fragments: true
  php_errors:
    log: true

  serializer:
    name_converter: 'serializer.name_converter.camel_case_to_snake_case'
